---@meta beacon
-- This file has been generated by utils/spec.lua

--- Simple beacon with window local highlighting

---@class beacon.conf.beacon: beacon.config
---@field color string the color of flash, can be color name or #RRGGBB
---@field count number how many times to flash
---@field interval number how long to flash
---@field on_line_change beacon.conf.beacon.on_line_change nil
---@field on_window_change beacon.conf.beacon.on_window_change nil

---@class beacon.conf.beacon.on_line_change: beacon.config
---@field enable boolean
---@field minimal_change number minimal amount of line change to trigger flash

---@class beacon.conf.beacon.on_window_change: beacon.config
---@field enable boolean
